### ISSUE TITLE
[CHORE] Dockerfile 변경

### ISSUE THREAD

**Issue by bongsh0112** [hook-killer/back-end#24]
# 🤖 Dockerfile 변경
- [x] jenkins 명령어로 환경변수 집어넣어줄 예정
- [x] NaverObjectStorage, MailUtil 관련 환경변수 수정사항 반영해야함
- [ ] k8s 오토스케일링 작업 시 변경 예정

**Comment by donsonioc2010** [comment]
k8s는 시간없음.
DockerFile변경 끝났으니 일단 Issue Close
