### ISSUE TITLE
[ISSUE, BUG] 타국어로 텍스트 입력시 Html 번역 이슈

### ISSUE THREAD

**Issue by lljh1992** [hook-killer/back-end#57]
# 📝 Summary
한국 -> 모든언어 가능
그외 언어로 입력시 번역불가

text 번역은 모든 언어에서 가능 
Html은 CN <-> EN의 상호 번역이 불가능
=> `PapagoTestController`에서 확인 가능

<img width="1214" alt="image" src="https://github.com/hook-killer/back-end/assets/80298461/7e2c9d7c-fba5-4433-8fab-b405f562987f">
<img width="1334" alt="image" src="https://github.com/hook-killer/back-end/assets/80298461/53e8230e-f5f7-4330-8797-4f38e0a43d09">

`add(translateService.naverPapagoHtmlTranslate(LanguageType.CN, LanguageType.EN, "<div>你好，我是帕帕戈。</div>"));`
`add(translateService.naverPapagoHtmlTranslate(LanguageType.EN, LanguageType.CN, "<div>Hello, I'm Papago.</div>"));`

얘네 둘이 문제임

## 🖌️ Rule
> ⚠️ **현재 상황** 
HTML Translate 일때 EN <-> CN의 경우만 아니라면 다이렉트하게 번역이 가능.
따라서 이 경우만 제외한 다른 상호번역은 현재 코드로도 사용이 가능함.

- source 언어가 CN 혹은 EN이라면, CN <-> EN 상호 번역 통신의 우선순위를 마지막으로 밀어버리고 먼저 KO로 번역 된 결과물을 Source 언어로 대체 사용하여 CN(Source 언어가 EN일때) 혹은 EN(Source 언어가 CN일때)으로 번역되도록 한다.
- 이런 방식을 쓸 시, CN -> KO -> EN 혹은 EN -> KO -> CN과 같은 이중 통신이 이루어지지 않을 것이다.

EX) 방법을 사용할 때와 사용하지 않을 때의 비교 CN -> EN의 경우
- 사용 시 : `CN -> KO` / `CN -> JP` / `KO(CN -> KO에서 도출된 값) -> EN` => `CN -> KO, JP, EN` 모두 도출 가능. 통신 단 3번
- 미사용 시 : `CN -> KO` /  `CN -> JP` / `CN -> KO -> EN` => `CN - > KO, JP, EN` 모두 도출이 가능하지만 통신은 4번

### 📚 Remarks
> ✅ 현재 TranslateService에 구현되어있는 API 통신 함수를 Article, Reply, Notice에서 모두 사용중

#### Article, Notice Create 시 **(Reply는 우리 서비스 특성상 html 번역이 필요없다!)**
- List<~~Content>를 반환하는 `TranslateService` 안의 함수를 쓸 수 있도록 `TranslateService` 를 주입받고 메소드 사용
- 물론 이 메소드 안에서 OrgLanguage를 고려한 조건부 번역이 모두 이루어져야 함
- 이 때 `saveAll(List<~~Content> list)` 시 `@Transactional` 불필요.

#### Article, Notice Update 시 **(Reply는 우리 서비스 특성상 html 번역이 필요없다!)**
- List<~~Content>를 반환하는 `TranslateService` 안의 함수를 쓸 수 있도록 `TranslateService` 를 주입받고 메소드 사용
- 물론 이 메소드 안에서 OrgLanguage를 고려한 조건부 번역이 모두 이루어져야 함
- 이 때 create와는 다르게 Update는 Dirty Checking 으로 변경 감지가 이루어짐.
- 따라서 `@Transactional(propagation)`을 이용해서 트랜잭션을 전파해주어야 할듯
- 트랜잭션 전파는 호출한 함수에서 일어나야 한다. 호출한 함수는 Article, Reply, Notice에서 `TranslateService`를 사용하는 함수들로 예상된다.

**Comment by donsonioc2010** [comment]
- create시에는 List<~Content> list를 반환하고 repository로 saveAll을 하면 되기 떄문에 `@Transactional`의 활용이 불필요 하다 생각됨.
- update시에는 `@Transactional`을 선언하고 return타입은 void로 해도 되겠다 생각되며, @Transactional선언을 하면서 상위(호출한 메소드의 Transactional)을 한개로 묶어서 같이 처리가 이뤄져야함.

확인방법은 SQL로 계속 업데이트문구 나가는지 확인하고, Content테이블이 Update되는건지 확인필요함.
