### ISSUE TITLE
공지사항 이슈

### ISSUE THREAD

**Issue by kwchoi11** [hook-killer/back-end#82]
어드민으로 로그인을 해도 어드민 전용 버튼이 렌더링 안 됨.
글 작성도 안 됨.
role이 undefined로 넘어옴.

**Comment by lljh1992** [comment]
http://hook-killer.sh-bong.site/notice/add 이렇게 입력시 작성창으로 넘어가짐

**Comment by donsonioc2010** [comment]
Jenkins빌드과정에서 Spring을 구버전으로 Docker Image생성하여 구버전을 배포하던 문제.
현재 최신화한 이후 해결.
